spring:
  datasource:
    # 💡 TiDB Cloud 권장 SSL 설정으로 변경했음!
    url: jdbc:mysql://gateway01.ap-northeast-1.prod.aws.tidbcloud.com:4000/test?useSSL=true&verifyServerCertificate=true
    username: 2EBXp9bbFQWPD6t.root
    # 💡 [중요] 일단 접속 확인을 위해 진짜 비밀번호를 ' ' 안에 직접 넣어서 테스트해보셈!
    password: ${TIDB_PASSWORD}

    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        "[format_sql]": true
        # 💡 TiDB와 가장 잘 맞는 MySQL 방언 설정임! [cite: 2026-02-19]
        dialect: org.hibernate.dialect.MySQLDialect

  thymeleaf:
    cache: false